version: '3.8'
services:
  app:
    build: .
    volumes:
      - .:/app
    ports:
      - "8000:80"
    command: python main.py
  db:
    image: postgres:latest
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: passwrd
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]  
      interval: 30s
      timeout: 10s
      retries: 5

  createdb:
    build: .
    command: python create_db.py
    depends_on:
      db:
        condition: service_healthy

