version: '3.8'
services:
  app:
    build: .
    ports:
      - "5000:5000"
    command: sh -c "python create_db.py && python main.py"
    restart: "no"
    depends_on:
      db:
        condition: service_healthy
  db:
    image: postgres:latest
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]  
      interval: 10s
      timeout: 10s
      retries: 5
    restart: "no"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      
volumes:
  postgres_data: