version: '3.8'
services:
  app:
    build: .
    volumes:
      - .:/app
    ports:
      - "8000:80"
    command: python main.py
    restart: "no"

  db:
    image: postgres:latest
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]  
      interval: 10s
      timeout: 10s
      retries: 5
    restart: "no"

  createdb:
    build: .
    command: python create_db.py
    depends_on:
      db:
        condition: service_healthy
    restart: "no"
