version: '3.8'
services:
  app:
    build: .
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5000:5000"
    command: sh -c "python create_db.py && python app.py"
    restart: "no"
    healthcheck:
      interval: 10s
      timeout: 10s
      retries: 5
    depends_on:
      db:
        condition: service_healthy
    networks:
      - mlops_network
  db:
    image: postgres:latest
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]  
      interval: 10s
      timeout: 10s
      retries: 5
    restart: "no"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - mlops_network
      
volumes:
  postgres_data:
    name: postgres_data

networks:
  mlops_network: