version: '3.8'

services:
  app:
    build: .
    volumes:
      - .:/app
    ports:
      - "8000:80"
    command: python main.py
  db:
      image: postgres:latest
      environment:
        POSTGRES_DB: postgres
        POSTGRES_USER: yourusername
        POSTGRES_PASSWORD: yourpassword
      ports:
        - "5432:5432"

    createdb:
      build: .
      command: python create_db.py
      depends_on:
        - db

