name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Install dependencies
      run: make install

    - name: Run tests
      env:
        PYTHONPATH: ${{ github.workspace }}
      run: make test

    - name: Format code
      run: make format

    - name: Build Docker image
      run: make build
      env:
        IMAGE_NAME: mlops_image
        TAG: latest

    - name: Run docker image
      run: make run

    - name: stop
      run: make stop
    
    - name: clean
      run: make clean

    - name: compose build
      run: make compose build

    - name: compose up
      run: make compose up

    - name: compose down
      run: make compose down